// src/components/layout/EmailDetail.vue
<script setup lang="ts">
import { ref, watch, computed } from "vue";
import { useEmailStore, useUIStore } from "@/stores";
import { useI18n } from "vue-i18n";
import { format } from "date-fns";
import { mockAISummary } from "@/mocks";
import { useDateLocale } from "@/composables/useDateLocale";
import {
    EmailOutlined,
    KeyboardArrowUpOutlined,
    KeyboardArrowDownOutlined,
    ReplyOutlined,
    ForwardOutlined,
    StarOutlined,
    StarBorderOutlined,
    ArchiveOutlined,
    DeleteOutlined,
    AttachFileOutlined,
    DescriptionOutlined,
    AutoAwesomeOutlined,
    NotesOutlined,
    TranslateOutlined,
    PictureAsPdfOutlined,
    ImageOutlined,
    VideoFileOutlined,
    AudioFileOutlined,
    TextSnippetOutlined,
    TableChartOutlined,
    FolderZipOutlined,
    ArticleOutlined,
    CodeOutlined,
    InsertDriveFileOutlined,
} from "@vicons/material";
import type { Component } from "vue";

// Stores
const emailStore = useEmailStore();
const uiStore = useUIStore();

// i18n
const { t } = useI18n();

// 日期格式化
const { currentDateLocale } = useDateLocale();

// AI 摘要
const aiSummary = ref("");
const isLoadingSummary = ref(false);

// 格式化完整日期
function formatFullDate(date: Date): string {
    const locale = currentDateLocale.value;
    return format(new Date(date), "yyyy年MM月dd日 EEEE HH:mm", {
        locale,
    });
}

// 获取头像首字母
function getInitials(name: string): string {
    return name.charAt(0).toUpperCase();
}

// 文件类型图标和颜色映射（基于行业标准 - Gmail、Apple Mail、Outlook）
const fileTypeMap: Record<string, { icon: Component; color: string }> = {
    // PDF - 红色
    'pdf': { icon: PictureAsPdfOutlined, color: '#F40F02' },
    // 图片 - 紫色
    'jpg': { icon: ImageOutlined, color: '#9C27B0' },
    'jpeg': { icon: ImageOutlined, color: '#9C27B0' },
    'png': { icon: ImageOutlined, color: '#9C27B0' },
    'gif': { icon: ImageOutlined, color: '#9C27B0' },
    'bmp': { icon: ImageOutlined, color: '#9C27B0' },
    'svg': { icon: ImageOutlined, color: '#9C27B0' },
    'webp': { icon: ImageOutlined, color: '#9C27B0' },
    'ico': { icon: ImageOutlined, color: '#9C27B0' },
    // 视频 - 橙色
    'mp4': { icon: VideoFileOutlined, color: '#FF9800' },
    'avi': { icon: VideoFileOutlined, color: '#FF9800' },
    'mov': { icon: VideoFileOutlined, color: '#FF9800' },
    'wmv': { icon: VideoFileOutlined, color: '#FF9800' },
    'flv': { icon: VideoFileOutlined, color: '#FF9800' },
    'mkv': { icon: VideoFileOutlined, color: '#FF9800' },
    'webm': { icon: VideoFileOutlined, color: '#FF9800' },
    // 音频 - 蓝色
    'mp3': { icon: AudioFileOutlined, color: '#2196F3' },
    'wav': { icon: AudioFileOutlined, color: '#2196F3' },
    'flac': { icon: AudioFileOutlined, color: '#2196F3' },
    'aac': { icon: AudioFileOutlined, color: '#2196F3' },
    'ogg': { icon: AudioFileOutlined, color: '#2196F3' },
    'm4a': { icon: AudioFileOutlined, color: '#2196F3' },
    'wma': { icon: AudioFileOutlined, color: '#2196F3' },
    // Microsoft Office 文档
    'doc': { icon: ArticleOutlined, color: '#2B579A' },   // Word 蓝色
    'docx': { icon: ArticleOutlined, color: '#2B579A' },
    'xls': { icon: TableChartOutlined, color: '#217346' }, // Excel 绿色
    'xlsx': { icon: TableChartOutlined, color: '#217346' },
    'ppt': { icon: ArticleOutlined, color: '#D24726' },   // PowerPoint 橙红色
    'pptx': { icon: ArticleOutlined, color: '#D24726' },
    // 其他文档
    'txt': { icon: TextSnippetOutlined, color: '#757575' },
    'rtf': { icon: TextSnippetOutlined, color: '#757575' },
    'odt': { icon: TextSnippetOutlined, color: '#757575' },
    'ods': { icon: TableChartOutlined, color: '#4CAF50' },
    'odp': { icon: ArticleOutlined, color: '#F57C00' },
    // 压缩包 - 绿色
    'zip': { icon: FolderZipOutlined, color: '#4CAF50' },
    'rar': { icon: FolderZipOutlined, color: '#4CAF50' },
    '7z': { icon: FolderZipOutlined, color: '#4CAF50' },
    'tar': { icon: FolderZipOutlined, color: '#4CAF50' },
    'gz': { icon: FolderZipOutlined, color: '#4CAF50' },
    // 代码 - 紫灰色
    'js': { icon: CodeOutlined, color: '#7E57C2' },
    'ts': { icon: CodeOutlined, color: '#7E57C2' },
    'html': { icon: CodeOutlined, color: '#7E57C2' },
    'css': { icon: CodeOutlined, color: '#7E57C2' },
    'json': { icon: CodeOutlined, color: '#7E57C2' },
    'xml': { icon: CodeOutlined, color: '#7E57C2' },
    'py': { icon: CodeOutlined, color: '#7E57C2' },
    'java': { icon: CodeOutlined, color: '#7E57C2' },
    'cpp': { icon: CodeOutlined, color: '#7E57C2' },
    'c': { icon: CodeOutlined, color: '#7E57C2' },
    'go': { icon: CodeOutlined, color: '#7E57C2' },
    'rs': { icon: CodeOutlined, color: '#7E57C2' },
    'php': { icon: CodeOutlined, color: '#7E57C2' },
    // 其他
    'exe': { icon: InsertDriveFileOutlined, color: '#607D8B' },
    'msi': { icon: InsertDriveFileOutlined, color: '#607D8B' },
};

// 获取附件图标
function getAttachmentIcon(filename: string): Component {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return fileTypeMap[ext]?.icon || DescriptionOutlined;
}

// 获取附件颜色
function getAttachmentColor(filename: string): string {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return fileTypeMap[ext]?.color || '#757575';
}

// 加载 AI 摘要
async function loadAISummary() {
    if (!emailStore.currentEmail) return;

    isLoadingSummary.value = true;
    try {
        // 模拟 AI 处理延迟
        await new Promise((resolve) => setTimeout(resolve, 800));
        aiSummary.value = mockAISummary(emailStore.currentEmail);
    } finally {
        isLoadingSummary.value = false;
    }
}

// 监听当前邮件变化
watch(
    () => emailStore.currentEmail,
    (newEmail) => {
        if (newEmail) {
            aiSummary.value = "";
            loadAISummary();
        }
    },
);

// 回复邮件
function handleReply() {
    uiStore.openComposeModal();
    // TODO: 设置回复数据
    //
    // 需要实现：
    // 1. 预填充收件人（来自 From 字段）
    // 2. 设置主题前缀 "Re: "
    // 3. 引用原文（添加 "> " 前缀）
    // 4. 设置回复引用的 Message-ID
    // 5. 区分回复全部 vs 回复发件人
}

// 转发邮件
function handleForward() {
    uiStore.openComposeModal();
    // TODO: 设置转发数据
    //
    // 需要实现：
    // 1. 预填充主题前缀 "Fwd: "
    // 2. 将原文作为附件或引用内容
    // 3. 保留原始邮件的完整信息
    // 4. 设置转发引用的 Message-ID
}

// 切换星标
function handleToggleStar() {
    if (emailStore.currentEmail) {
        emailStore.toggleStar(emailStore.currentEmail.id);
        const action = emailStore.currentEmail.starred
            ? t('email.starred')
            : t('email.archive');
        uiStore.showSuccess(action);
    }
}

// 删除邮件
function handleDelete() {
    if (emailStore.currentEmail) {
        emailStore.deleteEmail(emailStore.currentEmail.id);
        uiStore.showSuccess(t('email.trash'));
    }
}

// 归档邮件
function handleArchive() {
    if (emailStore.currentEmail) {
        emailStore.moveEmail(emailStore.currentEmail.id, "trash");
        uiStore.showSuccess(t('email.archive'));
    }
}

// 导航邮件
function handleNavigate(direction: "prev" | "next") {
    if (direction === "prev") {
        emailStore.navigatePrevious();
    } else {
        emailStore.navigateNext();
    }
}

// AI 操作
function handleAIAction(action: string) {
    switch (action) {
        case "reply":
            uiStore.showInfo(t('ai.generate'));
            break;
        case "summary":
            loadAISummary();
            break;
        case "translate":
            uiStore.showInfo(t('ai.translate'));
            break;
        case "tasks":
            uiStore.showInfo(t('ai.tasks'));
            break;
        default:
            uiStore.showInfo(`${t('common.operations')}: ${action}`);
    }
}

// AI 操作列表
const aiActions = computed(() => [
    { id: "reply", label: t('ai.smartReply'), icon: "reply" },
    { id: "summary", label: t('ai.summary'), icon: "summary" },
    { id: "translate", label: t('ai.translate'), icon: "translate" },
    { id: "tasks", label: t('ai.tasks'), icon: "tasks" },
]);
</script>

<template>
    <div class="detail-panel">
        <!-- 空状态 -->
        <div v-if="!emailStore.currentEmail" class="empty-state">
            <div class="empty-icon">
                <EmailOutlined :size="48" />
            </div>
            <h3>{{ t('email.noEmails') }}</h3>
            <p>{{ t('email.noEmails') }}</p>
        </div>

        <!-- 邮件详情 -->
        <div v-else class="email-detail">
            <!-- 顶部工具栏 -->
            <div class="detail-header">
                <div class="detail-nav">
                    <button
                        class="icon-btn"
                        :disabled="!emailStore.hasPreviousEmail"
                        @click="handleNavigate('prev')"
                        :title="t('email.from')"
                    >
                        <KeyboardArrowUpOutlined :size="20" />
                    </button>
                    <button
                        class="icon-btn"
                        :disabled="!emailStore.hasNextEmail"
                        @click="handleNavigate('next')"
                        :title="t('email.to')"
                    >
                        <KeyboardArrowDownOutlined :size="20" />
                    </button>
                </div>
            </div>

            <!-- 邮件主题 -->
            <h2 class="detail-subject">
                {{ emailStore.currentEmail.subject }}
            </h2>

            <!-- 邮件元信息 -->
            <div class="detail-meta">
                <div class="sender-info">
                    <div
                        class="sender-avatar"
                        :style="{
                            backgroundColor:
                                emailStore.currentEmail.accountId || '#7C3AED',
                        }"
                    >
                        {{ getInitials(emailStore.currentEmail.sender) }}
                    </div>
                    <div class="sender-details">
                        <div class="sender-name">
                            {{ emailStore.currentEmail.sender }}
                        </div>
                        <div class="sender-email">
                            &lt;{{ emailStore.currentEmail.senderEmail }}&gt;
                        </div>
                    </div>
                </div>
                <div class="email-meta-info">
                    <div class="email-date">
                        {{ formatFullDate(emailStore.currentEmail.date) }}
                    </div>
                    <div class="email-to">
                        {{ t('email.to') }}: {{ emailStore.currentEmail.recipient }}
                    </div>
                </div>
            </div>

            <!-- AI 摘要卡片 -->
            <div v-if="isLoadingSummary || aiSummary" class="ai-card">
                <div class="ai-card-header">
                    <div class="ai-badge">
                        <AutoAwesomeOutlined :size="16" />
                        <span>{{ t('ai.summary') }}</span>
                    </div>
                </div>
                <div class="ai-card-content">
                    <div
                        v-if="isLoadingSummary"
                        class="skeleton skeleton-text"
                        style="width: 90%"
                    ></div>
                    <div v-else>
                        <ul>
                            <li
                                v-for="(line, index) in aiSummary.split('\n')"
                                :key="index"
                            >
                                {{ line.replace("• ", "") }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- 邮件正文 -->
            <div
                class="detail-body"
                v-html="emailStore.currentEmail.body"
            ></div>

            <!-- 附件区域 -->
            <div
                v-if="emailStore.currentEmail.attachments.length > 0"
                class="attachments-section"
            >
                <div class="attachments-header">
                    <AttachFileOutlined :size="18" />
                    <span>{{ t('email.attachments') }} ({{ emailStore.currentEmail.attachments.length }})</span>
                </div>
                <div class="attachments-list">
                    <div
                        v-for="(attachment, index) in emailStore.currentEmail
                            .attachments"
                        :key="index"
                        class="attachment-item"
                    >
                        <div class="attachment-icon" :style="{ color: getAttachmentColor(attachment.name) }">
                            <component :is="getAttachmentIcon(attachment.name)" :size="24" />
                        </div>
                        <div class="attachment-info">
                            <div class="attachment-name">
                                {{ attachment.name }}
                            </div>
                            <div class="attachment-size">
                                {{ attachment.size }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 操作按钮栏 -->
            <div class="detail-actions">
                <button class="icon-btn" @click="handleReply" :title="t('email.reply')">
                    <ReplyOutlined :size="18" />
                </button>
                <button
                    class="icon-btn"
                    @click="handleForward"
                    :title="t('email.forward')"
                >
                    <ForwardOutlined :size="18" />
                </button>
                <button
                    class="icon-btn"
                    @click="handleToggleStar"
                    :title="t('email.starred')"
                >
                    <StarOutlined
                        v-if="emailStore.currentEmail.starred"
                        :size="18"
                        style="color: #f59e0b"
                    />
                    <StarBorderOutlined v-else :size="18" />
                </button>
                <button
                    class="icon-btn"
                    @click="handleArchive"
                    :title="t('email.archive')"
                >
                    <ArchiveOutlined :size="18" />
                </button>
                <button
                    class="icon-btn danger"
                    @click="handleDelete"
                    :title="t('common.delete')"
                >
                    <DeleteOutlined :size="18" />
                </button>
            </div>

            <!-- AI 操作栏 -->
            <div class="ai-actions">
                <div class="ai-actions-label">
                    <AutoAwesomeOutlined :size="16" />
                    <span>AI {{ t('ai.provider') }}</span>
                </div>
                <div class="ai-actions-buttons">
                    <button
                        v-for="action in aiActions"
                        :key="action.id"
                        class="ai-action-btn"
                        @click="handleAIAction(action.id)"
                    >
                        <ReplyOutlined v-if="action.icon === 'reply'" :size="16" />
                        <NotesOutlined v-else-if="action.icon === 'summary'" :size="16" />
                        <TranslateOutlined v-else-if="action.icon === 'translate'" :size="16" />
                        <NotesOutlined v-else :size="16" />
                        <span>{{ action.label }}</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>
.email-detail {
    display: flex;
    flex-direction: column;
    height: 100%;
}

.detail-actions {
    padding: 12px 20px;
    border-top: 1px solid var(--border-subtle);
    border-bottom: 1px solid var(--border-subtle);
    display: flex;
    align-items: center;
    gap: 4px;
}

/* 附件区域样式 */
.attachments-section {
    padding: 16px 20px;
    border-top: 1px solid var(--border-subtle);
    border-bottom: 1px solid var(--border-subtle);
}

.attachments-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 12px;
    font-size: 14px;
    font-weight: 500;
    color: var(--text-secondary);
}

.attachments-list {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
}

.attachment-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    background: var(--bg-glass);
    border: 1px solid var(--border-subtle);
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.2s ease;
    min-width: 0;
    flex-shrink: 0;
}

.attachment-item:hover {
    background: var(--bg-glass-hover);
    border-color: var(--primary-color);
}

.attachment-icon {
    flex-shrink: 0;
    color: var(--text-muted);
}

.attachment-info {
    min-width: 0;
    flex: 1;
    overflow: hidden;
}

.attachment-name {
    font-size: $font-size-base;
    font-weight: $font-weight-medium;
    color: var(--text-primary);
    word-break: break-word;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.attachment-size {
    font-size: 12px;
    color: var(--text-muted);
    margin-top: 2px;
}

.skeleton-text {
    height: 14px;
    margin-bottom: 8px;
    background: linear-gradient(
        90deg,
        var(--bg-glass) 25%,
        var(--bg-glass-hover) 50%,
        var(--bg-glass) 75%
    );
    background-size: 200% 100%;
    animation: skeleton-loading 1.5s infinite;
    border-radius: 4px;
}

@keyframes skeleton-loading {
    0% {
        background-position: 200% 0;
    }
    100% {
        background-position: -200% 0;
    }
}
</style>

// src/lib/components/email/EmailDetail.svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import { getI18nState } from '$lib/stores/i18n.svelte';
  import { getEmailState } from '$lib/stores/email.svelte';
  import type ComposeModal from './ComposeModal.svelte';
  import DOMPurify from 'dompurify';
  import { ChevronUp, ChevronDown, Layers, Paperclip, Reply, Forward, Star, Archive, Trash2, Mail } from 'lucide-svelte';

  const COMPOSE_MODAL_KEY = Symbol.for('compose-modal');
  const getComposeModal = getContext<() => ComposeModal | undefined>(COMPOSE_MODAL_KEY);

  const i18n = getI18nState();
  const t = $derived(i18n.t);
  const emailState = getEmailState();

  let aiSummary = $state('');
  let isLoadingSummary = $state(false);

  function getInitials(name: string): string {
    return name.charAt(0).toUpperCase();
  }

  function formatFullDate(timestamp: number): string {
    return new Date(timestamp * 1000).toLocaleString(undefined, {
      year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit',
    });
  }

  async function loadAISummary() {
    if (!emailState.selectedEmail) return;
    isLoadingSummary = true;
    try {
      await new Promise(resolve => setTimeout(resolve, 800));
      aiSummary = '• 邮件主要内容摘要\n• 需要关注的关键点\n• 建议的后续行动';
    } finally {
      isLoadingSummary = false;
    }
  }

  function handleToggleStar() {
    if (emailState.selectedEmail) {
      emailState.toggleStar(emailState.selectedEmail.id);
    }
  }

  function handleDelete() {
    if (emailState.selectedEmail) {
      emailState.deleteEmails([emailState.selectedEmail.id]);
    }
  }

  // H-03: 使用 stale flag 防止 race condition
  let summaryRequestId = 0;
  $effect(() => {
    const email = emailState.selectedEmail;
    if (email) {
      aiSummary = '';
      const currentId = ++summaryRequestId;
      isLoadingSummary = true;
      new Promise(resolve => setTimeout(resolve, 800)).then(() => {
        if (currentId === summaryRequestId) {
          aiSummary = '• 邮件主要内容摘要\n• 需要关注的关键点\n• 建议的后续行动';
          isLoadingSummary = false;
        }
      });
    }
  });

  const aiActions = $derived([
    { id: 'reply', label: t.ai.smartReply },
    { id: 'summary', label: t.ai.summary },
    { id: 'translate', label: t.ai.translate },
    { id: 'tasks', label: t.ai.tasks },
  ]);

  function getFileExtensionColor(filename: string): string {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    const colors: Record<string, string> = {
      pdf: '#F40F02', jpg: '#9C27B0', jpeg: '#9C27B0', png: '#9C27B0',
      gif: '#9C27B0', svg: '#9C27B0', webp: '#9C27B0',
      mp4: '#FF9800', avi: '#FF9800', mov: '#FF9800', mkv: '#FF9800',
      mp3: '#2196F3', wav: '#2196F3', flac: '#2196F3', aac: '#2196F3',
      doc: '#2B579A', docx: '#2B579A', xls: '#217346', xlsx: '#217346',
      ppt: '#D24726', pptx: '#D24726',
      txt: '#757575', zip: '#4CAF50', rar: '#4CAF50', '7z': '#4CAF50',
    };
    return colors[ext] || '#757575';
  }

  function getFileExtensionLabel(filename: string): string {
    return filename.split('.').pop()?.toUpperCase() || 'FILE';
  }
</script>

<div class="detail-panel flex h-full flex-1 flex-col bg-background">
  {#if emailState.selectedEmail}
    <!-- Top toolbar: nav arrows -->
    <div class="flex items-center justify-between border-b border-border px-5 py-2">
      <div class="flex items-center gap-1">
        <button class="icon-btn-sm flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-glass-hover hover:text-foreground" title={t.email.from}>
          <ChevronUp size={20} />
        </button>
        <button class="icon-btn-sm flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-glass-hover hover:text-foreground" title={t.email.to}>
          <ChevronDown size={20} />
        </button>
      </div>
    </div>

    <!-- Subject -->
    <div class="border-b border-border px-5 py-4">
      <h2 class="text-xl font-semibold text-foreground">
        {emailState.selectedEmail.subject || '(No Subject)'}
      </h2>
    </div>

    <!-- Sender meta -->
    <div class="flex items-center gap-3 border-b border-border px-5 py-3">
      <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/15 text-sm font-semibold text-primary">
        {getInitials(emailState.selectedEmail.sender_name || emailState.selectedEmail.sender_email)}
      </div>
      <div class="min-w-0 flex-1">
        <div class="flex items-center gap-2">
          <span class="text-sm font-medium text-foreground">
            {emailState.selectedEmail.sender_name || emailState.selectedEmail.sender_email}
          </span>
          <span class="truncate text-xs text-muted-foreground">
            &lt;{emailState.selectedEmail.sender_email}&gt;
          </span>
        </div>
        <div class="mt-0.5 text-xs text-muted-foreground">
          {t.email.to}: {emailState.selectedEmail.recipient_emails}
          {#if emailState.selectedEmail.cc_emails}
            &nbsp;|&nbsp; {t.email.cc}: {emailState.selectedEmail.cc_emails}
          {/if}
        </div>
      </div>
      <span class="shrink-0 text-xs text-muted-foreground">
        {formatFullDate(emailState.selectedEmail.sent_at)}
      </span>
    </div>

    <!-- Scrollable content area -->
    <div class="flex-1 overflow-y-auto">
      <!-- AI Summary card -->
      {#if isLoadingSummary || aiSummary}
        <div class="ai-card mx-5 mt-4 rounded-lg border border-primary/20 bg-primary/5">
          <div class="flex items-center gap-2 px-4 py-2.5">
            <Layers size={16} class="text-primary" />
            <span class="text-xs font-semibold text-primary">{t.ai.summary}</span>
          </div>
          <div class="border-t border-primary/10 px-4 py-3">
            {#if isLoadingSummary}
              <div class="space-y-2">
                <div class="skeleton skeleton-text" style="width: 90%"></div>
                <div class="skeleton skeleton-text" style="width: 75%"></div>
                <div class="skeleton skeleton-text" style="width: 60%"></div>
              </div>
            {:else}
              <ul class="space-y-1">
                {#each aiSummary.split('\n') as line}
                  <li class="text-sm text-foreground/80">{line.replace('• ', '')}</li>
                {/each}
              </ul>
            {/if}
          </div>
        </div>
      {/if}

      <!-- Email body -->
      <div class="px-5 py-4">
        {#if emailState.selectedEmail.body_html}
          {@html DOMPurify.sanitize(emailState.selectedEmail.body_html)}
        {:else}
          <pre class="whitespace-pre-wrap text-sm leading-relaxed text-foreground/90">{emailState.selectedEmail.body_text || ''}</pre>
        {/if}
      </div>

      <!-- Attachments -->
      {#if emailState.selectedEmail.has_attachments}
        <div class="border-t border-border px-5 py-4">
          <div class="mb-3 flex items-center gap-2 text-sm font-medium text-muted-foreground">
            <Paperclip size={18} />
            <span>{t.email.attachments}</span>
          </div>
          <div class="flex flex-wrap gap-3">
            <!-- Placeholder attachment items -->
            <div class="attachment-item flex items-center gap-2 rounded-lg border border-border bg-glass px-3 py-2 transition-colors hover:border-primary hover:bg-glass-hover">
              <div class="flex h-8 w-8 items-center justify-center rounded bg-blue-500/10 text-xs font-bold text-blue-500">PDF</div>
              <div class="min-w-0">
                <div class="truncate text-sm font-medium text-foreground">document.pdf</div>
                <div class="text-xs text-muted-foreground">2.4 MB</div>
              </div>
            </div>
          </div>
        </div>
      {/if}
    </div>

    <!-- Action buttons -->
    <div class="flex items-center gap-1 border-t border-border px-5 py-2">
      <button class="icon-btn-sm flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-glass-hover hover:text-foreground" title={t.email.reply} onclick={() => {
        const modal = getComposeModal?.();
        if (emailState.selectedEmail && modal) {
          modal.showReply(
            emailState.selectedEmail.sender_email,
            emailState.selectedEmail.subject || '',
            emailState.selectedEmail.body_text || ''
          );
        }
      }}>
        <Reply size={18} />
      </button>
      <button class="icon-btn-sm flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-glass-hover hover:text-foreground" title={t.email.forward} onclick={() => {
        const modal = getComposeModal?.();
        if (emailState.selectedEmail && modal) {
          modal.showForward(
            emailState.selectedEmail.subject || '',
            emailState.selectedEmail.body_text || ''
          );
        }
      }}>
        <Forward size={18} />
      </button>
      <button
        class="icon-btn-sm flex h-8 w-8 items-center justify-center rounded-md transition-colors hover:bg-glass-hover {emailState.selectedEmail.is_starred ? 'text-yellow-400' : 'text-muted-foreground hover:text-foreground'}"
        title={t.email.star}
        onclick={handleToggleStar}
      >
        <Star size={18} class={emailState.selectedEmail.is_starred ? 'fill-current' : ''} />
      </button>
      <button class="icon-btn-sm flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-glass-hover hover:text-foreground" title={t.email.archive}>
        <Archive size={18} />
      </button>
      <button
        class="icon-btn-sm flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-glass-hover hover:text-destructive"
        title={t.common.delete}
        onclick={handleDelete}
      >
        <Trash2 size={18} />
      </button>
    </div>

    <!-- AI Actions bar -->
    <div class="flex items-center gap-3 border-t border-border px-5 py-2">
      <div class="flex items-center gap-1.5 text-xs text-muted-foreground">
        <Layers size={14} class="text-primary" />
        <span>AI {t.ai.provider}</span>
      </div>
      <div class="flex items-center gap-1">
        {#each aiActions as action}
          <button class="ai-action-btn flex items-center gap-1 rounded-md px-2.5 py-1 text-xs text-muted-foreground transition-colors hover:bg-primary/10 hover:text-primary">
            <span>{action.label}</span>
          </button>
        {/each}
      </div>
    </div>
  {:else}
    <!-- Empty state -->
    <div class="flex h-full flex-col items-center justify-center py-12">
      <Mail size={48} class="mb-4 opacity-30" strokeWidth={1} />
      <h3 class="text-lg text-foreground/70">{t.email.noEmailSelected}</h3>
    </div>
  {/if}
</div>
